CREATE TABLE LEAGUE (
	id SERIAL PRIMARY KEY, 
	isPublic BOOLEAN NOT NULL,
	name VARCHAR(80) UNIQUE NOT NULL,
	inheritsGamesFromLeague_id INTEGER
); 

ALTER TABLE LEAGUE ADD CONSTRAINT LEAGUE_LEAGUE_FK FOREIGN KEY(inheritsGamesFromLeague_id) REFERENCES LEAGUE(ID);

CREATE TABLE INVITATION (
	id SERIAL PRIMARY KEY, 
	league_id INTEGER NOT NULL,
	email VARCHAR(80) UNIQUE NOT NULL
);

ALTER TABLE INVITATION ADD CONSTRAINT INVITATION_LEAGUE_FK FOREIGN KEY(league_id) REFERENCES LEAGUE(ID);
 
CREATE TABLE UTILISATEUR (
 	id SERIAL PRIMARY KEY, 
   	login VARCHAR(80) UNIQUE NOT NULL,
   	password VARCHAR(80) NOT NULL,
   	admin BOOLEAN NOT NULL,
   	displayName VARCHAR(80) NOT NULL,
	DEFAULT_LEAGUE_ID INTEGER
);

ALTER TABLE UTILISATEUR ADD CONSTRAINT UTILISATEUR_LEAGUE_FK FOREIGN KEY(DEFAULT_LEAGUE_ID) REFERENCES LEAGUE(ID);

CREATE TABLE LEAGUE_PARTICIPATION (
	id SERIAL PRIMARY KEY, 
	utilisateur_id INTEGER NOT NULL,
	league_id INTEGER NOT NULL,
	admin BOOLEAN NOT NULL,
	POINTS INTEGER,
	NB_CORRECT_RESULTS INTEGER,
	NB_EXACT_SCORES INTEGER,
	NB_COMPUTED_PRONOS INTEGER
); 

ALTER TABLE LEAGUE_PARTICIPATION ADD CONSTRAINT LEAGUE_PARTICIPATION_LEAGUE_FK FOREIGN KEY(league_id) REFERENCES LEAGUE(ID);

ALTER TABLE LEAGUE_PARTICIPATION ADD CONSTRAINT LEAGUE_PARTICIPATION_USER_FK FOREIGN KEY(utilisateur_id) REFERENCES UTILISATEUR(ID);
   	
CREATE TABLE GAME (
	id SERIAL PRIMARY KEY,
	team1 VARCHAR(80) NOT NULL,
	team2 VARCHAR(80) NOT NULL,
	scoreTeam1 INTEGER,
	scoreTeam2 INTEGER,
	date DATE NOT NULL,
	closed BOOLEAN NOT NULL,
	pointsComputed BOOLEAN NOT NULL,
	league_id INTEGER NOT NULL
);

ALTER TABLE GAME ADD CONSTRAINT GAME_LEAGUE_FK FOREIGN KEY(league_id) REFERENCES LEAGUE(ID);

CREATE TABLE PRONOSTIC (
	id SERIAL PRIMARY KEY,
	scoreTeam1 INTEGER NOT NULL,
	scoreTeam2 INTEGER NOT NULL,
	points INTEGER,
	utilisateur_id INTEGER NOT NULL,
	game_id INTEGER NOT NULL
);

ALTER TABLE PRONOSTIC ADD CONSTRAINT PRONOSTIC_UTILISATEUR_FK FOREIGN KEY(utilisateur_id) REFERENCES UTILISATEUR(ID);

ALTER TABLE PRONOSTIC ADD CONSTRAINT PRONOSTIC_GAME_FK FOREIGN KEY(game_id) REFERENCES GAME(ID);